apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - disallow-privileged.yaml
  - require-requests-limits.yaml
  - disallow-host-namespaces.yaml
  - require-run-as-nonroot.yaml
  - restrict-image-registries.yaml
