apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny.yaml
  - allow-gateway-ingress.yaml
  - allow-oidc-ingress.yaml
  - allow-egress.yaml
  - allow-prometheus-scrape.yaml
