apiVersion: v1
kind: Service
metadata:
  name: filestash
  namespace: filestash
  labels:
    app: filestash
spec:
  type: ClusterIP
  ports:
    - port: 8334
      targetPort: 8334
      protocol: TCP
      name: http
  selector:
    app: filestash
